// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Solution.Domain.DbContexts;

namespace Warehouse.Solution.Domain.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20220712123041_ref1")]
    partial class ref1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ProductoProductoMarca", b =>
                {
                    b.Property<Guid>("MarcasId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductosId")
                        .HasColumnType("char(36)");

                    b.HasKey("MarcasId", "ProductosId");

                    b.HasIndex("ProductosId");

                    b.ToTable("ProductoProductoMarca");
                });

            modelBuilder.Entity("ProductoProductoUso", b =>
                {
                    b.Property<Guid>("ProductosId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsosId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductosId", "UsosId");

                    b.HasIndex("UsosId");

                    b.ToTable("ProductoProductoUso");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Catalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Catalogo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abreviatura = "ACT",
                            Descripcion = "Registro activo",
                            Nombre = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Abreviatura = "IACT",
                            Descripcion = "Registro inactivo",
                            Nombre = "Inactivo"
                        },
                        new
                        {
                            Id = 10,
                            Abreviatura = "FACS",
                            Descripcion = "Factura Stoack",
                            Nombre = "Factura-Stock"
                        },
                        new
                        {
                            Id = 11,
                            Abreviatura = "GAST",
                            Descripcion = "Gastos",
                            Nombre = "Gastos"
                        });
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioCrea")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioModifica")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoDocumentoId")
                        .HasColumnType("char(1)");

                    b.Property<string>("Ubigeo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Actividad")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CuentaBancaria1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CuentaBancaria2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("IdUsuarioCrea")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioModifica")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RepresentanteLegal")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TextoComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoDocumentoId")
                        .HasColumnType("char(1)");

                    b.Property<string>("Ubigeo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("urlImagen")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("empresa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d79cde1-babd-44dc-ac5a-9379afa68a75"),
                            FechaCreacion = new DateTime(2022, 7, 12, 7, 30, 41, 414, DateTimeKind.Local).AddTicks(9631),
                            FechaInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "FARMACIA RAMOS S.A.",
                            Vigente = true
                        },
                        new
                        {
                            Id = new Guid("3785474b-f656-4d49-99c6-c144708d6a62"),
                            FechaCreacion = new DateTime(2022, 7, 12, 7, 30, 41, 418, DateTimeKind.Local).AddTicks(4885),
                            FechaInicio = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "MINIMARKETS RAMOS S.A.",
                            Vigente = true
                        });
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.EmpresaSucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioCrea")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioModifica")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("empresa_sucursal");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e84ee21d-48bc-4ef7-978a-a0ae02520904"),
                            Direccion = "Av. Los angeles 232",
                            FechaCreacion = new DateTime(2022, 7, 12, 7, 30, 41, 418, DateTimeKind.Local).AddTicks(5397),
                            IdEmpresa = new Guid("9d79cde1-babd-44dc-ac5a-9379afa68a75"),
                            Nombre = "Farmacia Principal de Los Olivos",
                            Vigente = true
                        },
                        new
                        {
                            Id = new Guid("4649554b-ab5e-4647-866e-1cc4e4b50ffa"),
                            Direccion = "Av. Caceres de Hurre 122",
                            FechaCreacion = new DateTime(2022, 7, 12, 7, 30, 41, 418, DateTimeKind.Local).AddTicks(6003),
                            IdEmpresa = new Guid("3785474b-f656-4d49-99c6-c144708d6a62"),
                            Nombre = "Minimarket los Olivos 1",
                            Vigente = true
                        },
                        new
                        {
                            Id = new Guid("9414a1d9-c237-4e95-9d76-3290ecb1c551"),
                            Direccion = "Av. Proceres 121",
                            FechaCreacion = new DateTime(2022, 7, 12, 7, 30, 41, 418, DateTimeKind.Local).AddTicks(6043),
                            IdEmpresa = new Guid("3785474b-f656-4d49-99c6-c144708d6a62"),
                            Nombre = "Minimarket los Olivos 2",
                            Vigente = true
                        });
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.EmpresaUnidadMedida", b =>
                {
                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdUnidadMedida")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UnidadMedidaId")
                        .HasColumnType("char(2)");

                    b.HasKey("IdEmpresa", "IdUnidadMedida");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("empresa_unidad_medida");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.EntidadFinanciera", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(2)")
                        .HasColumnName("Id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("entidad_financiera");

                    b.HasData(
                        new
                        {
                            Id = "01",
                            Nombre = "CENTRAL RESERVA DEL PERU"
                        },
                        new
                        {
                            Id = "02",
                            Nombre = "DE CREDITO DEL PERU"
                        },
                        new
                        {
                            Id = "03",
                            Nombre = "INTERNACIONAL DEL PERU"
                        },
                        new
                        {
                            Id = "05",
                            Nombre = "LATINO"
                        },
                        new
                        {
                            Id = "07",
                            Nombre = "CITIBANK DEL PERU S.A."
                        },
                        new
                        {
                            Id = "08",
                            Nombre = "STANDARD CHARTERED"
                        },
                        new
                        {
                            Id = "09",
                            Nombre = "SCOTIABANK PERU"
                        },
                        new
                        {
                            Id = "11",
                            Nombre = "CONTINENTAL"
                        },
                        new
                        {
                            Id = "12",
                            Nombre = "DE LIMA"
                        },
                        new
                        {
                            Id = "16",
                            Nombre = "MERCANTIL"
                        },
                        new
                        {
                            Id = "18",
                            Nombre = "NACION"
                        },
                        new
                        {
                            Id = "22",
                            Nombre = "SANTANDER CENTRAL HISPANO"
                        },
                        new
                        {
                            Id = "23",
                            Nombre = "DE COMERCIO"
                        },
                        new
                        {
                            Id = "25",
                            Nombre = "REPUBLICA"
                        },
                        new
                        {
                            Id = "26",
                            Nombre = "NBK BANK"
                        },
                        new
                        {
                            Id = "29",
                            Nombre = "BANCOSUR"
                        },
                        new
                        {
                            Id = "35",
                            Nombre = "FINANCIERO DEL PERU"
                        },
                        new
                        {
                            Id = "37",
                            Nombre = "DEL PROGRESO"
                        },
                        new
                        {
                            Id = "38",
                            Nombre = "INTERAMERICANO FINANZAS"
                        },
                        new
                        {
                            Id = "39",
                            Nombre = "BANEX"
                        },
                        new
                        {
                            Id = "40",
                            Nombre = "NUEVO MUNDO"
                        },
                        new
                        {
                            Id = "41",
                            Nombre = "SUDAMERICANO"
                        },
                        new
                        {
                            Id = "42",
                            Nombre = "DEL LIBERTADOR"
                        },
                        new
                        {
                            Id = "43",
                            Nombre = "DEL TRABAJO"
                        },
                        new
                        {
                            Id = "44",
                            Nombre = "SOLVENTA"
                        },
                        new
                        {
                            Id = "45",
                            Nombre = "SERBANCO SA."
                        },
                        new
                        {
                            Id = "46",
                            Nombre = "BANK OF BOSTON"
                        },
                        new
                        {
                            Id = "47",
                            Nombre = "ORION"
                        },
                        new
                        {
                            Id = "48",
                            Nombre = "DEL PAIS"
                        },
                        new
                        {
                            Id = "49",
                            Nombre = "MI BANCO"
                        },
                        new
                        {
                            Id = "50",
                            Nombre = "BNP PARIBAS"
                        },
                        new
                        {
                            Id = "53",
                            Nombre = "HSBC BANK PERU S.A."
                        },
                        new
                        {
                            Id = "99",
                            Nombre = "OTROS"
                        });
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.FormaPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("forma_pago");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.ImpuestoMoneda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AbreviaturaImpuesto")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioCrea")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioModifica")
                        .HasColumnType("char(36)");

                    b.Property<string>("NombreMoneda")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("PorcentajeImpuesto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SimboloMoneda")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("impuesto_moneda");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Laboratorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("Laboratorio");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.MotivoNotaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("motivo_nota_credito");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("CierreAnual")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarra")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioCrea")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioModifica")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("PrecioVenta2")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioVentaMayor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioVentaUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("RegistroSanitario")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StockEgreso")
                        .HasColumnType("int");

                    b.Property<int>("StockIngreso")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("UbicacionAlmacen")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("stockSaldo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.ProductoCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioCrea")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioModifica")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("producto_categoria");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.ProductoMarca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("producto_marca");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.ProductoUso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("producto_uso");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("IdTipoDocumento")
                        .HasColumnType("char(1)")
                        .HasColumnName("IdTipoDocumento");

                    b.Property<int>("IdTipoProveedor")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdUsuarioCrea")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioModifica")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEmpresaSucursal");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoDocumento");

                    b.HasIndex("IdTipoProveedor");

                    b.ToTable("proveedor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e7da830-71a2-4758-9b21-ec7d0dda7984"),
                            Correo = "proveedordemedicamentos@gmail.com",
                            Direccion = "Jr. Mira flores, calle 2 pabellon 52",
                            FechaCreacion = new DateTime(2022, 7, 12, 7, 30, 41, 418, DateTimeKind.Local).AddTicks(7275),
                            IdEmpresa = new Guid("9d79cde1-babd-44dc-ac5a-9379afa68a75"),
                            IdEmpresaSucursal = new Guid("e84ee21d-48bc-4ef7-978a-a0ae02520904"),
                            IdEstado = 1,
                            IdTipoDocumento = "6",
                            IdTipoProveedor = 10,
                            Nombre = "Proveedor de mecicamentos S.A.",
                            NumeroDocumento = "20718623451",
                            Telefono = "10-12222-22",
                            Vigente = true
                        });
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.TipoComprobantePago", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(2)")
                        .HasColumnName("Id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tipo_comprobante_pago");

                    b.HasData(
                        new
                        {
                            Id = "00",
                            Nombre = "Otros"
                        },
                        new
                        {
                            Id = "01",
                            Nombre = "Factura"
                        },
                        new
                        {
                            Id = "02",
                            Nombre = "Recibo por Honorarios"
                        },
                        new
                        {
                            Id = "03",
                            Nombre = "Boleta de Venta"
                        },
                        new
                        {
                            Id = "04",
                            Nombre = "Liquidación de compra"
                        },
                        new
                        {
                            Id = "07",
                            Nombre = "Nota de crédito"
                        },
                        new
                        {
                            Id = "08",
                            Nombre = "Nota de débito"
                        },
                        new
                        {
                            Id = "09",
                            Nombre = "Guía de remisión - Remitente"
                        },
                        new
                        {
                            Id = "10",
                            Nombre = "Recibo por Arrendamiento"
                        },
                        new
                        {
                            Id = "12",
                            Nombre = "Ticket o cinta emitido por máquina registradora"
                        },
                        new
                        {
                            Id = "31",
                            Nombre = "Guía de Remisión - Transportista"
                        });
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.TipoDocumentoIdentidad", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(1)")
                        .HasColumnName("Id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tipo_documento_identidad");

                    b.HasData(
                        new
                        {
                            Id = "0",
                            Nombre = "OTROS TIPOS DE DOCUMENTOS"
                        },
                        new
                        {
                            Id = "1",
                            Nombre = "DOCUMENTO NACIONAL DE IDENTIDAD (DNI)"
                        },
                        new
                        {
                            Id = "4",
                            Nombre = "CARNET DE EXTRANJERIA"
                        },
                        new
                        {
                            Id = "6",
                            Nombre = "REGISTRO ÚNICO DE CONTRIBUYENTES"
                        },
                        new
                        {
                            Id = "7",
                            Nombre = "PASAPORTE"
                        },
                        new
                        {
                            Id = "A",
                            Nombre = "CÉDULA DIPLOMÁTICA DE IDENTIDAD"
                        });
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.TipoNotaCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("tipo_nota_credito");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.TipoOperacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(2)")
                        .HasColumnName("Id");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdEmpresaSucursal")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("tipo_operacion");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Ubigeo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoDepartamento")
                        .HasColumnType("char(2)")
                        .HasColumnName("CodigoDepartamento");

                    b.Property<string>("CodigoDistrito")
                        .HasColumnType("char(2)")
                        .HasColumnName("CodigoDistrito");

                    b.Property<string>("CodigoProvincia")
                        .HasColumnType("char(2)")
                        .HasColumnName("CodigoProvincia");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("IdUsuarioCrea")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdUsuarioModifica")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Ubigeo");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.UnidadMedida", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(2)")
                        .HasColumnName("Id");

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("unidad_medida");

                    b.HasData(
                        new
                        {
                            Id = "01",
                            Nombre = "KILOGRAMOS"
                        },
                        new
                        {
                            Id = "02",
                            Nombre = "LIBRAS"
                        },
                        new
                        {
                            Id = "03",
                            Nombre = "TONELADAS LARGAS"
                        },
                        new
                        {
                            Id = "04",
                            Nombre = "TONELADAS MÉTRICAS"
                        },
                        new
                        {
                            Id = "05",
                            Nombre = "TONELADAS CORTAS"
                        },
                        new
                        {
                            Id = "06",
                            Nombre = "GRAMOS"
                        },
                        new
                        {
                            Id = "07",
                            Nombre = "UNIDADES"
                        },
                        new
                        {
                            Id = "08",
                            Nombre = "LITROS"
                        },
                        new
                        {
                            Id = "09",
                            Nombre = "GALONES"
                        },
                        new
                        {
                            Id = "10",
                            Nombre = "BARRILES"
                        },
                        new
                        {
                            Id = "11",
                            Nombre = "LATAS"
                        },
                        new
                        {
                            Id = "12",
                            Nombre = "CAJAS"
                        },
                        new
                        {
                            Id = "13",
                            Nombre = "MILLARES"
                        },
                        new
                        {
                            Id = "14",
                            Nombre = "METROS CÚBICOS"
                        },
                        new
                        {
                            Id = "15",
                            Nombre = "METROS"
                        },
                        new
                        {
                            Id = "99",
                            Nombre = "OTROS (ESPECIFICAR)"
                        });
                });

            modelBuilder.Entity("ProductoProductoMarca", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.ProductoMarca", null)
                        .WithMany()
                        .HasForeignKey("MarcasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Solution.Domain.Model.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductoProductoUso", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Solution.Domain.Model.ProductoUso", null)
                        .WithMany()
                        .HasForeignKey("UsosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Cliente", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.TipoDocumentoIdentidad", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Empresa", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.TipoDocumentoIdentidad", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.EmpresaSucursal", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.Empresa", "Empresa")
                        .WithMany("EmpresaSucursales")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.EmpresaUnidadMedida", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.Empresa", "Empresa")
                        .WithMany("EmpresaUnidadMedidas")
                        .HasForeignKey("EmpresaId");

                    b.HasOne("Warehouse.Solution.Domain.Model.UnidadMedida", "UnidadMedida")
                        .WithMany("EmpresaUnidadMedidas")
                        .HasForeignKey("UnidadMedidaId");

                    b.Navigation("Empresa");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Laboratorio", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.Producto", null)
                        .WithMany("Laboratorios")
                        .HasForeignKey("ProductoId");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Producto", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.ProductoCategoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Proveedor", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.Empresa", "Empresa")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Solution.Domain.Model.EmpresaSucursal", "EmpresaSucursal")
                        .WithMany()
                        .HasForeignKey("IdEmpresaSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Solution.Domain.Model.Catalogo", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Warehouse.Solution.Domain.Model.TipoDocumentoIdentidad", "TipoDocumentoIdentidad")
                        .WithMany()
                        .HasForeignKey("IdTipoDocumento");

                    b.HasOne("Warehouse.Solution.Domain.Model.Catalogo", "TipoProveedor")
                        .WithMany()
                        .HasForeignKey("IdTipoProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("EmpresaSucursal");

                    b.Navigation("Estado");

                    b.Navigation("TipoDocumentoIdentidad");

                    b.Navigation("TipoProveedor");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.UnidadMedida", b =>
                {
                    b.HasOne("Warehouse.Solution.Domain.Model.Producto", null)
                        .WithMany("UnidadesMedida")
                        .HasForeignKey("ProductoId");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Empresa", b =>
                {
                    b.Navigation("EmpresaSucursales");

                    b.Navigation("EmpresaUnidadMedidas");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.Producto", b =>
                {
                    b.Navigation("Laboratorios");

                    b.Navigation("UnidadesMedida");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.ProductoCategoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Warehouse.Solution.Domain.Model.UnidadMedida", b =>
                {
                    b.Navigation("EmpresaUnidadMedidas");
                });
#pragma warning restore 612, 618
        }
    }
}
